### ISSUE TITLE
ocf_heartbeat_nfsserver error

### ISSUE THREAD

**Issue by jurim76** [ClusterLabs/resource-agents#807] opened 2016-05-12 14:18 UTC
Error entry in log:

`lrmd[809]: notice: p_nfsserver_monitor_10000:38242:stderr [/usr/lib/ocf/resource.d/heartbeat/nfsserver: 284: [: missing ] ]`

crm definition:
`primitive p_nfsserver ocf:heartbeat:nfsserver params nfs_init_script="/etc/init.d/nfs-kernel-server" op monitor depth="0" timeout="20s" interval="10"`

Debian 8 Jessie
pacemaker-1.1.14-3 (sid build)
resource-agents-3.9.7-1 (sid build)

**Comment by krig** [comment] 2016-05-12 15:38
Looking at the `nfsserver` implementation, I suspect that these are dash vs. bash issues with defining and using local variables on the same line, as on line 280:

```
local cmd=$1
```

**Comment by dmuhamedagic** [comment] 2016-05-13 10:33
On Thu, May 12, 2016 at 07:18:56AM -0700, jurim76 wrote:
> Debian 8 Jessie
> pacemaker-1.1.14-3 (sid build)
> resource-agents-3.9.7-1 (sid build)

Can you please provide the resource agents version:

grep Build.version /usr/lib/ocf/lib/heartbeat/ocf-shellfuncs

**Comment by jurim76** [comment] 2016-05-13 15:25
Hi Dejan,

# Build version: 0174fb10132d8895c1dde9b75fe9ee71cccb1807

On Fri, May 13, 2016 at 1:33 PM, Dejan Muhamedagic <notifications@github.com

**Comment by dmuhamedagic** [comment] 2016-05-17 15:09
On Fri, May 13, 2016 at 08:25:38AM -0700, jurim76 wrote:
> # Build version: 0174fb10132d8895c1dde9b75fe9ee71cccb1807

Hmm, I still get the same line which doesn't invoke '[' :

280     local cmd=$1
281     set_exec_mode
282 
283     if [ $EXEC_MODE -eq 2 ]; then
284         systemctl $cmd nfs-lock.service

My guess is that there's a patch in the package. Could you take
a peek at the nfsserver script and show the relevant lines.
Thanks!

**Comment by krig** [comment] 2016-05-17 16:13
Could this be something @dhoffend knows about? Since it's Debian.

**Comment by krig** [comment] 2016-05-17 16:19
Very strange, looking at the Debian package sources I don't see any suspicious patch:

* https://anonscm.debian.org/cgit/debian-ha/resource-agents.git/tree/debian/patches?h=debian/3.9.7-1&id=c6b7c98f68552420a04c9443e152e4203115296c

* https://anonscm.debian.org/cgit/debian-ha/resource-agents.git/tree/heartbeat/nfsserver?h=debian/3.9.7-1&id=c6b7c98f68552420a04c9443e152e4203115296c

**Comment by dhoffend** [comment] 2016-05-17 16:31
Sounds a bit like the local variable issue I already encountered in clvm.

I can take a closer look later

**Comment by jurim76** [comment] 2016-05-17 20:06
Hi Dejan,

I've upgraded from resource-agents-3.9.7-1 to resource-agents-3.9.7-3 and
the error message disappear.

Diffs between versions

resource-agents-3.9.7-1: (perhaps some patch)
280   local cmd=$1
281   set_exec_mode
282
283   if [ $EXEC_MODE -eq 1 ]; then
284      if [ "$cmd" = "status"]; then
285       systemctl $cmd nfs-common.service >/dev/null

resource-agents-3.9.7-3
280   local cmd=$1
281   set_exec_mode
282
283   if [ $EXEC_MODE -eq 2 ]; then
284     systemctl $cmd nfs-lock.service

Thank you for your support!

On Tue, May 17, 2016 at 6:10 PM, Dejan Muhamedagic <notifications@github.com

**Comment by krig** [comment] 2016-05-17 20:34
Alright, closing the issue. Thanks!

**Closed by krig** 2016-05-17 20:34 UTC
Labels: bug

**Comment by dhoffend** [comment] 2016-05-17 20:42
Cool. I was just playing around with the nfsserver resource and wasn't able to reproduce the error. But maybe it's still worth to take a closer because debian doesn't have nfs-lock.service or whatever. Under debian it's nfs-kernel-śerver.service.

The init script you configured is basically just a wrapper around systemctl ... so why now add an additional exec_mode to target the debian specific systemd unit instead of using the wrapper init script.

What's wondering me is: exec_mode 1 == init script. but then having the line that checks for CMD=STATUS and then executing systemctl .. that really sounds like a broken patched script. especially since the nfsserver ra hasn't been touched in a while

**Comment by dhoffend** [comment] 2016-05-17 20:57
Oh well ... forget it ... there's no nfs-server unit-file in debian. It's just the nfs-kernel-server init script that gets loaded into systemctl and apears to be a systemctl service but in fact is a init script...

**Comment by dmuhamedagic** [comment] 2016-05-18 08:42
On Tue, May 17, 2016 at 01:06:14PM -0700, jurim76 wrote:
> Hi Dejan,
> 
> I've upgraded from resource-agents-3.9.7-1 to resource-agents-3.9.7-3 and
> the error message disappear.
> 
> Diffs between versions
> 
> resource-agents-3.9.7-1: (perhaps some patch)
> 280   local cmd=$1
> 281   set_exec_mode
> 282
> 283   if [ $EXEC_MODE -eq 1 ]; then
> 284      if [ "$cmd" = "status"]; then

Here's the problem, missing space before ']'. Don't be fooled by
quotes, after the shell digests (expands) this, the command is
rendered thus:

      [ whatever$cmdexpandsto = status]

and [ (aka test) won't see the closing ']'.
