### ISSUE TITLE
live migration of VirtualDomain resource using ssh and not port 49152 possible ?

### ISSUE THREAD

**Issue by e-ferrari** [ClusterLabs/resource-agents#979] opened 2017-05-17 11:10 UTC
Hi,

i stumbled upon this:
https://github.com/ClusterLabs/resource-agents/issues/489?_pjax=%23js-repo-pjax-container
I'm having the same problem. I'd like to migrate using ssh and not opening an extra port (49152).
But, although setting migration_transport=ssh, the VirtualDomain RA chooses port 49152 to live migrate.
Is the problem now fixed ? 

Thanks.

Bernd

**Comment by dmuhamedagic** [comment] 2017-06-12 11:48
You can set the --migrateuri option in the migrate_options parameter. See the description of that parameter.

**Comment by dhoffend** [comment] 2017-07-31 08:54
Keep in mind that you need 2 seperate connections for live migration. 
* The first connection is used for control traffic (that's where ssh comes into play) that announces the vm configuration on the receiving node and opens/prepares ...
* a second connection for the state transfer (ram content, etc.). The default is a plain tcp connection without encryption/authentication for speed using the ports 49152+(rand 64).

If you dislike this behavior you must use the --migrateuri argument in the migration_options parameter. But the the current implenentation lacks a few granular options (like non-root ssh users for live migration)

If you like better control over your live migration maybe take a look into my Pull Request #1004 

IMO this his not a bug and should be closed.

**Comment by krig** [comment] 2017-08-08 06:14
Closing in favor of PR #1004 as suggested.

**Closed by krig** 2017-08-08 06:14 UTC
